### ISSUE TITLE
Failed on fresh version installation

### ISSUE THREAD

**Issue by estatic** [facebook/pyre-check#216]
I've just tried to install Pyre on my laptop and got this:
`$ pip install Pyre-check
Collecting Pyre-check
  Downloading https://files.pythonhosted.org/packages/1a/3e/ac9126cfb9db76746f9bfd1c224384ef5ed9a250d7a254bb5c917d63ee0b/pyre-check-0.0.32.tar.gz (57kB)
    100% |████████████████████████████████| 61kB 953kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\IVAN_G~1\AppData\Local\Temp\pip-install-17y3kfh1\Pyre-check\setup.py", line 25, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'`

**Comment by phe-sto** [comment]
Similar issue on a Windows10 computer.

**Comment by mattjw** [comment]
Similar issue on an alpine docker image. Specifically, the public image `python:3.6.8`.

I'm installing via pipenv: `pipenv install pyre-check==0.0.x`.

The failure seems dependant on the pyre version...

- `0.0.30` success
- `0.0.31` failure: README.md not found
- `0.0.32` failure: README.md not found
- `0.0.33` failure: no matching distro found
- `0.0.34` failure: no matching distro found
- `0.0.35` failure: no matching distro found
- `0.0.36` success
- `0.0.37` failure: README.md not found
- `0.0.38` failure: no matching distro found
- `0.0.39` failure: README.md not found

Here's some messages from the various failure/success cases...

```
root@9850954d08e1:/home# pipenv install pyre-check==0.0.33
Installing pyre-check==0.0.33…
Adding pyre-check to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock (988c98) out of date, updating to (7b022b)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (988c98)!
Installing dependencies from Pipfile.lock (988c98)…
An error occurred while installing pyre-check==0.0.33 --hash=sha256:0f66251700445e5d57bd42bdbb395cbb4ad2e9babb5ec01442e76ab87914fa13 --hash=sha256:c7ff814903426b06aa40112547aa191056b7aeb5688f998ec18bc9ec1a5c5624! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 9/9 — 00:00:01
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: []
[pipenv.exceptions.InstallError]: ['ERROR: Could not find a version that satisfies the requirement pyre-check==0.0.33 (from -r /tmp/pipenv-9fqcd4gi-requirements/pipenv-xxx46lzp-requirement.txt (line 1)) (from versions: 0.0.29-macosx_10_11_x86_64, 0.0.30, 0.0.31, 0.0.32, 0.0.36, 0.0.37, 0.0.39)', 'ERROR: No matching distribution found for pyre-check==0.0.33 (from -r /tmp/pipenv-9fqcd4gi-requirements/pipenv-xxx46lzp-requirement.txt (line 1))']
```

```
root@9850954d08e1:/home# pipenv install pyre-check==0.0.36
Installing pyre-check==0.0.36…
Adding pyre-check to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock (19029c) out of date, updating to (988c98)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (19029c)!
Installing dependencies from Pipfile.lock (19029c)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 9/9 — 00:00:01
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

```
root@9850954d08e1:/home# pipenv install pyre-check==0.0.37
Installing pyre-check==0.0.37…
Adding pyre-check to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock (9185b3) out of date, updating to (19029c)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (9185b3)!
Installing dependencies from Pipfile.lock (9185b3)…
An error occurred while installing pyre-check==0.0.37 --hash=sha256:13c5e683b276d61c33598b616dd7b252730cdb6640daa5a18a1576dee3c9a3c1 --hash=sha256:4c33196d7423771b7b25b3dd7340ab60e5499e796e69f1aef1507e465d7466d0 --hash=sha256:ab012f2f2e7efed66b2452d32393505c79429fd123cf99efd6bed3f44c124cf5! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 9/9 — 00:00:01
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting pyre-check==0.0.37', '  Using cached pyre-check-0.0.37.tar.gz (68 kB)']
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '     command: /root/.local/share/virtualenvs/home-oTyxYuqD/bin/python -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-9bfym8wu/pyre-check/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-9bfym8wu/pyre-check/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /tmp/pip-install-9bfym8wu/pyre-check/pip-egg-info', '         cwd: /tmp/pip-install-9bfym8wu/pyre-check/', '    Complete output (5 lines):', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/tmp/pip-install-9bfym8wu/pyre-check/setup.py", line 54, in <module>', '        with open("README.md") as f:', "    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:
```

**Comment by thefallentree** [comment]
+1, this is happening to me as well

**Comment by MaggieMoss** [comment]
Apologies for the frustrating experience, taking a look at what might be causing this now.

**Comment by thefallentree** [comment]
This issue happens for me on Mac and linux , 3.6 and 3.7,  0.0.37 and 0.0.39 both have issue (can't install 0.0.38 anymore for some reason)

**Comment by thefallentree** [comment]
```
Non-user install because user site-packages disabled
Created temporary directory: /private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-ephem-wheel-cache-ed3o7ffq
Created temporary directory: /private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-req-tracker-28k3mguy
Initialized build tracking at /private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-req-tracker-28k3mguy
Created build tracker: /private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-req-tracker-28k3mguy
Entered build tracker: /private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-req-tracker-28k3mguy
Created temporary directory: /private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-install-7s1hflj9
1 location(s) to search for versions of pyre-check:
* https://pypi.org/simple/pyre-check/
Fetching project page and analyzing links: https://pypi.org/simple/pyre-check/
Getting page https://pypi.org/simple/pyre-check/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pyre-check/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pyre-check/ HTTP/1.1" 304 0
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/32/b0/8f074bf76214cafa5e88bbebc676df70396a66211333331790844df61adb/pyre_check-0.0.6-py3-none-macosx_10_11_x86_64.whl#sha256=2d631e00c15761bdeef0e3f70e3b54f8cfa2765018d42a841cbfe7373574db6d (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/f3/d9/f8382029c06b46b990628a71c04f8c8fd92adf2088e5d6cc92ea8b2c07d3/pyre_check-0.0.6-py3-none-manylinux1_x86_64.whl#sha256=a05d569441a1eadc5acbb8574710d69171898a2c02fa196e1d162faf77dc4f02 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/7c/6b/fe0d1313d78f2d3edd2fbb1c9e7ded1ba06092916789baf163933844870e/pyre_check-0.0.7-py3-none-macosx_10_11_x86_64.whl#sha256=1ca118242d4c3cee4ddf8d55234064ff1b16288c56949ff55e85c4d2dec6fd67 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/dd/c1/89a1daa94e1c5be6d66e3b259a323fa38eca7a3305186a39bbc5a8d807a2/pyre_check-0.0.7-py3-none-manylinux1_x86_64.whl#sha256=a9ed2d1a16e14cdf8248045dbf9f8ec0089e0f6c8dfc9c1262de1c6c103bbb6b (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/56/43/529cdcd759ad6c5a1e8690f5ffb30f04b653c4920f4a2e66c4b20c001f5d/pyre_check-0.0.8-py3-none-macosx_10_11_x86_64.whl#sha256=15342472ca40dec9efa1ca8d243d2bf52e8c2492daeb5b97e3310f4eec5321db (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/5d/0e/ae2f20d2276179ac97437d3d2c8bd1c2eb99d41cb900b342cc84e674ae9c/pyre_check-0.0.8-py3-none-manylinux1_x86_64.whl#sha256=d753b2958cf7fdf5cf33cde39c9324129b942e23c8a122e6c9adc51364392540 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/00/99/64cfa27244b61b471332bb0fe18d9acdf55191962878a5f5241f7a818c03/pyre_check-0.0.9-py3-none-macosx_10_11_x86_64.whl#sha256=462633233cc5191d0932792a733d597fc0ce8ff7c25e854d25d2a518235649cd (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/74/eb/16f658758fd456e75179a163241c38c0ce6e401c41ba233e69df206e3b3e/pyre_check-0.0.9-py3-none-manylinux1_x86_64.whl#sha256=07e1c283ac59dbdd5702545276f226937a96cc16c204b8440fb541c68c2ac762 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/de/db/e2078127d43bada807d2f99abaf0256c1106f4ffc5ece807b15b02ffb518/pyre_check-0.0.10-py3-none-macosx_10_11_x86_64.whl#sha256=6781cd47c248700d01e8e7a27b2c43489e974a0f7b9a86d9cda91fdc14a82b6b (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/7c/3a/f72325487baf0cf82a51348f17fae8efe17935680d7dfe8d830fe6e553be/pyre_check-0.0.10-py3-none-manylinux1_x86_64.whl#sha256=d83239b381c05f8fd15802eb385052d56b37f80121906c5e3d35c475b6f1bb21 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/0f/d4/e36fe2d30d9a46d1b80860a9d0bd34b8aab25b7e8a55a2feae8c6b84437a/pyre_check-0.0.11-py3-none-macosx_10_11_x86_64.whl#sha256=8d50101ded45abcfafcf89bc6b4988606f716cc38b5db2ab6b7a3d11ad31f224 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/f1/f4/1bb2848bec1c2736b3ec2052d06871365dd00fbb0994d16851a4d484ba29/pyre_check-0.0.11-py3-none-manylinux1_x86_64.whl#sha256=aa20622324c273d52b7ff9a34b0680a4e4cb134e1b43e6efb3181b03a62889c6 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/bb/99/21b796af99aeff41a71b08a238f01fff47086611d59b153951e33c6f9767/pyre_check-0.0.12-py3-none-macosx_10_11_x86_64.whl#sha256=25da29fc78ed9e71d1edc26c0e9ae05a4729c4c111d6b856f85cf5bc1e5ee73d (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/7c/c6/394458bfff46b9347a03cb260348552040d7428f2beb13651ca1adfcae6e/pyre_check-0.0.12-py3-none-manylinux1_x86_64.whl#sha256=ab7852a3b512f9f28dba11deb2855eb5512d170ddb363f091ad09849d9c8777a (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/3a/86/a3402c1fb899b331cc6f6f156777a70137cdb093bdf39baf16407bfe9e86/pyre_check-0.0.14-py3-none-macosx_10_11_x86_64.whl#sha256=9b89a49956c129a41f18aef3566844da25cbd9e7487d19fe4e7304fae895d2ee (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/06/cb/2e8d640b487e5b963122d978954d8544e8d9044e21510900e62705df69f9/pyre_check-0.0.14-py3-none-manylinux1_x86_64.whl#sha256=9a7b772a288b920e1c4e20c5aef5babd8c37465030c1977169b9c80dc2c257e1 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/82/6f/1ee5bbc1ee2a002f26adaef291084fd1e45df70d8806080181ca0e79ba40/pyre_check-0.0.15-py3-none-macosx_10_11_x86_64.whl#sha256=15490163f0e8334e771b1d168a3ab045e38296db1d1bdc587c4676b6557cfbf1 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/74/bc/beb6a2fc72f1b6c6a3637dec032eb815136d169ecc1e9b2f81bfa59b08c6/pyre_check-0.0.15-py3-none-manylinux1_x86_64.whl#sha256=c1da99d9a911b5046b830e468c529a9dd17a9537e52ca94e75ea07fdeab2b97c (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/33/20/03ab82575216c026072df22a47a6589e67e358393e3bf3ed622fdf98e0e5/pyre_check-0.0.16-py3-none-macosx_10_11_x86_64.whl#sha256=303bdb52ae3337318a7242684d4d32ce608d4a787e84c22d618b3a1e7b7cf4e3 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/51/fe/e1a682738475ca1515161f497d742c47262aa31340d54f685f0e70dd26ad/pyre_check-0.0.16-py3-none-manylinux1_x86_64.whl#sha256=e0a026b5aae6a23370df9117abdcb39d4124b972fa2cff45227a63780cf369ca (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/32/73/1353d0b88019bbea479e416ec6bbba2d55d28521e96fb52ad75cab586e4a/pyre_check-0.0.17-py3-none-macosx_10_11_x86_64.whl#sha256=c3b0892c51697a953a81d8c864a0a4f01a9a9ee32a2effc58072a054eb4c8534 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/de/6a/08be30a978f6012273b531a7a96163cab3d1b44f4ea7614e471520e1561e/pyre_check-0.0.17-py3-none-manylinux1_x86_64.whl#sha256=5b46332cb07a6c21fbfa0a74fab256bcffa91d62e3acbcfa1cf4d932552ab920 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/8d/20/d8fa07161187a74c79ce2176b1da84a0354c76016725c9484dcbc95b7136/pyre_check-0.0.18-py3-none-macosx_10_11_x86_64.whl#sha256=67a73338b0327cda08f09722704843fe932a36c987b1978664592969dfbc7c85 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/b8/78/365dd3d8faf4e11fe4d4f2401aa0c054835174532fd810b5eef45a9212b0/pyre_check-0.0.18-py3-none-manylinux1_x86_64.whl#sha256=0952e915149f2373d763dea61574e89225eb26ffd105f66264bbecac79f58a97 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/fc/33/87641ca3400e74dad8484df16189fbb0f925eb3e5a2402eecacb95ed1896/pyre_check-0.0.19-py3-none-macosx_10_11_x86_64.whl#sha256=793835b14dc282451e2426197dcb7b3403e6ca8c82fb986278e92898ec8e9460 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/7a/1e/9a394b2dcf8f15f66d7b250061ae4cc6fe7e6e8711ca42762b1093f3598e/pyre_check-0.0.19-py3-none-manylinux1_x86_64.whl#sha256=bc61dd0eaca75142869f0d54b9310bf932336cd7d96212db8c17a9cb0752dc40 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/ee/e3/ea29aaac9013e244ac2aa82c17aabf228cfff8e8394849b00ef3144c8a89/pyre_check-0.0.20-py3-none-macosx_10_11_x86_64.whl#sha256=5be0c254ead5cf06cce6910b7806a0c0d0b742254b40862f5f1d5646a05d1f94 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/76/f4/6d93942a5a96823e776a91fdaf477013bf4d2bfb14592870e42b1774e464/pyre_check-0.0.20-py3-none-manylinux1_x86_64.whl#sha256=4c7102417c5ca47bfae693630d6a20740260752a809b0fa75b52af0de4944c66 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/d1/37/35af7e39a94ef2a3b66ca553c1b48d44ea94c35a1ee5d77983d94974c7bb/pyre_check-0.0.21-py3-none-macosx_10_11_x86_64.whl#sha256=56ab921e374bf2622eee63323dcd779594f0e283e17b97daaa25f0e6c2469f2e (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/bc/a2/43b3694c0237be28cd3cd610d3fb4aedbb43570423c4766dad693bb8ddac/pyre_check-0.0.21-py3-none-manylinux1_x86_64.whl#sha256=4593eceebeb2f8bf316f545dd3a020e95d8ff1e478048dd63c1d71e86a6dd8ad (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/bf/6e/873485d9f0186a909b81e97d4656ff0611b1fce8506d6166f4cf51c70ea7/pyre_check-0.0.22-py3-none-macosx_10_11_x86_64.whl#sha256=f487967685f8292cc82e90199f4104b8fbdae338f3736c55ed9375e7de4580c4 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/f9/22/8116ccf5a829538ce0add7701f4bce4ac15863feb24a0aaad204c381f91a/pyre_check-0.0.22-py3-none-manylinux1_x86_64.whl#sha256=dac3c1a958dbe2987d8fbd0b1f89958b8121176fa1bc2ee1353eb18859c8b052 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/c1/82/20c25dbaabdd139d9385e45a26987d33f8659c2a76734572a7084aa59e52/pyre_check-0.0.23-py3-none-macosx_10_11_x86_64.whl#sha256=69141a3225665db3cb2ad587da04971ea4ed73964e919d9c4ba5864ff494ab19 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/c3/09/b34bc21721b30d925f1219a05465ee5595621f97a6b1c5d5d161f6fb2021/pyre_check-0.0.23-py3-none-manylinux1_x86_64.whl#sha256=e5ec21ad053be34f598cb9ff036f6060d39face848e9f0fe626d03c28ed21071 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/f1/88/305a442dacb96e0e2eb9e1e8dbf683e6bfbb7e06e1f5505e1453632fc78b/pyre_check-0.0.24-py3-none-macosx_10_11_x86_64.whl#sha256=af9dd88b5ed8836b28831897803a6495d1ec04837451b2be104f8a8b011a1264 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/0c/fb/f4fcdc8cac347fdf8f6fb9d7715ecf05f69d039ba015785d1c0cffb67be5/pyre_check-0.0.24-py3-none-manylinux1_x86_64.whl#sha256=0475cc0de6497ab4a466ee3aa21203fa3d5d177aead4de5d069ed03b682562d9 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/ca/ac/64cb75219225358dcd819f38b8b9caa833d5c88cb7652985e7fc5d953036/pyre_check-0.0.25-py3-none-macosx_10_11_x86_64.whl#sha256=0d09128353cb896e8616a192dc40e016b9f9e3d396fdca228357c9e43e490305 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/82/23/1887a8440f3ab9653c553aa98dc06c9cba69c362c0103cf0a6d3c7efe93d/pyre_check-0.0.25-py3-none-manylinux1_x86_64.whl#sha256=f7321bf4fe172c38909f57ec59e8190d329670a9858f4f2e67ae699842645612 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/d2/e1/d4cf3c2a0e9a84a6518f9e7fdfc0f492fa6b674aa498747ac74c811048c5/pyre_check-0.0.26-py3-none-macosx_10_11_x86_64.whl#sha256=53092acb9667f3c349efef92c089c15b5c82ca5bddde20bc49eb01d16925aab6 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/9e/39/45c00102b169e995f36e635982ca998118debf3c4d2abc1a7cf09670351f/pyre_check-0.0.26-py3-none-manylinux1_x86_64.whl#sha256=909429e5957a3d1934bf5e230461f56e3be02a3ec2d4a5a403d7fc8c8d201fa1 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/66/f1/88ad6bdb09b3dd09b779d6a0d6d70a06bd5157095924a758efa93c107ee0/pyre_check-0.0.27-py3-none-macosx_10_11_x86_64.whl#sha256=f8c6289e92461145e2fdf9118b09b0a327e6f180798c1863b3c915e5e7a99ff4 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/7c/b2/b1e1f38876acf87b08fd7e8df4baaf3c2aaa08f25d7f83ae384655c63705/pyre_check-0.0.27-py3-none-manylinux1_x86_64.whl#sha256=f6f1f182dce5fea068b91c28ee62b010ca6e2ea90df617a637fe91b5d4b2ced1 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/a4/a5/4e66f0b36600833f8678fd818edf404fa61c13063afb3ae828e950276bea/pyre_check-0.0.28-py3-none-macosx_10_11_x86_64.whl#sha256=6b0e49c4f94f10970b9f84e55196c02b22d12947e5777fc1b5ceedebc1fb9328 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/5f/b8/e0bb9cb77ba5da5d0c65082eb9742b5e870e9f5a5c87dd0e52f7cb3ae93f/pyre_check-0.0.28-py3-none-manylinux1_x86_64.whl#sha256=1a41669387566a75a0610058feefd7fe4457ddd123464306783e87884993df09 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Found link https://files.pythonhosted.org/packages/88/34/92d4ae95b9dc90084e5828c5e868de4bc0597ef944ef3d1968f39f716070/pyre-check-0.0.29-macosx_10_11_x86_64.tar.gz#sha256=f7872b0e8b6def017aaf71e2406f7067b40c3926a6ab3087fb0c9a5bd8214c5c (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.29-macosx_10_11_x86_64
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/ca/22/de5af049b1bdac87e1ef3c1bb5d43af0b36dbde5209644a28d2492eb27ee/pyre_check-0.0.29-py3-none-macosx_10_11_x86_64.whl#sha256=82b741a054ee09df7fdf3a129372d82cb2d5519fb9d5a905561d187b40b07963 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/34/04/a54481670e06d31df988f1acc84f5d621685276c8ca774a390934ba793ef/pyre_check-0.0.29-py3-none-manylinux1_x86_64.whl#sha256=6bcc705d4f9f758fab8055164e6fa2aa47f5fcf863fb4b7b7b1f47a11e83b183 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Found link https://files.pythonhosted.org/packages/69/4c/d45d75ff044075389b8f044fe9817648eb24a047cd55275674d1d9ee162b/pyre-check-0.0.30.tar.gz#sha256=f01a306401a48258edc32997064917a0ad7d110cc903ca6e31fbecf6ccccba17 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.30
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/88/f6/677106a193429b25ebbfd326c6fa7a315bc6f26fac05ae5f64dd5728c702/pyre_check-0.0.30-py3-none-macosx_10_11_x86_64.whl#sha256=62d4a387870306102b3731fbe91cce69cd369dc0134a6132f80a5f45ef0f89cc (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/79/91/362920c7bc49233bbe3c417ba30eb8af199e1269725c47775c8c03b5f1ab/pyre_check-0.0.30-py3-none-manylinux1_x86_64.whl#sha256=1233ac69fd93160777784c7c5b36d53466b71e4c8105068cf74215b7737cbd1f (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Found link https://files.pythonhosted.org/packages/97/c0/f7a1b73dbf71f3b58713cf246d594f23297ed5c5388afa198708e9a16e4b/pyre-check-0.0.31.tar.gz#sha256=918dbdf7d564ae158b2bfd507525ed760b32d772b5c82f88284f4672c01fe50f (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.31
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/91/4b/92bf79a44ebbf5094f6a3767d51e3b955da9e2e3f807591dff4352953bcb/pyre_check-0.0.31-py3-none-macosx_10_11_x86_64.whl#sha256=402ee60c3f9e23061967a9d0ea57ca92902d4a5876d46ae439c3b76c5f6fb97a (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/d9/63/1d90c35cf2fe749ff5b8895a29817c0e133eaa3899d3d534cde5231f2fd2/pyre_check-0.0.31-py3-none-manylinux1_x86_64.whl#sha256=0722b8edc7b83a6a0309e3f472a0ccc4b3e17d21de12b3b84eef353cec866364 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Found link https://files.pythonhosted.org/packages/1a/3e/ac9126cfb9db76746f9bfd1c224384ef5ed9a250d7a254bb5c917d63ee0b/pyre-check-0.0.32.tar.gz#sha256=58190046d0c374c9ee486c34e010a9c2795767699d13d56c23e3d7f619bff038 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.32
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/0a/22/dcd6ab52b398e353fce7f2b2754b1bab4ef5945e6fd39d3fdbba04fef44c/pyre_check-0.0.32-py3-none-macosx_10_11_x86_64.whl#sha256=beee8afb468c7d1e5429d2dabcabcadb0e85cfeff17432686940adb6d31032be (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/62/36/8cd44650ce234d1c73cfff363c0eb4abdcc93ff0b7aceebc21b36e286586/pyre_check-0.0.32-py3-none-manylinux1_x86_64.whl#sha256=4b5eb0796e33930eaf1beb6e5f086e018474f6da640387d5871ec6c39ba82b1f (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/7a/95/fe5ada739b81392180578f75bd8377ec3f699af5b47c2a7fd2f24c6732fa/pyre_check-0.0.33-py3-none-macosx_10_11_x86_64.whl#sha256=c7ff814903426b06aa40112547aa191056b7aeb5688f998ec18bc9ec1a5c5624 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/85/01/66770922a30b9d9b2a86aa05de1c0f2a74ea48d9d0fc41c7586ce2d8cea5/pyre_check-0.0.33-py3-none-manylinux1_x86_64.whl#sha256=0f66251700445e5d57bd42bdbb395cbb4ad2e9babb5ec01442e76ab87914fa13 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Found link https://files.pythonhosted.org/packages/ac/c5/9eb377eaf32a2e63f1d62f518a5f89068e2071d0bf2b12ffb1973089ca99/pyre-check-0.0.36.tar.gz#sha256=130ddc4e3abf431a04f42845288149253a1f5a8804d3a03b4faca958805c2ee3 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.36
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/10/65/29479e76f9b64f35e566a8753147709378c7cde0bd70861adfd762abc6fd/pyre_check-0.0.36-py3-none-macosx_10_11_x86_64.whl#sha256=b4eef3a4e3593999d8e60e7d79eb5e1306116fbc8e44f7c93e439ba7ba09ef55 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/bf/ce/37641d5085e993a246bfd51332b5d3e6589583849716007e8cd877feda41/pyre_check-0.0.36-py3-none-manylinux1_x86_64.whl#sha256=c8b7757dd9920340c6bfd564d66b5d269f5a928180ff9d60e2f722aac2848d77 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Found link https://files.pythonhosted.org/packages/61/9f/2584ef32c5b39c05e8dcacf168b1b8039d5df5de0ad70a35a07be70e109e/pyre-check-0.0.37.tar.gz#sha256=ab012f2f2e7efed66b2452d32393505c79429fd123cf99efd6bed3f44c124cf5 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.37
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/1c/2e/d89a95a8b35e9d66ddd0a3bf4967b069e7f6d03d2c7aee5bb2188b202d9d/pyre_check-0.0.37-py3-none-macosx_10_11_x86_64.whl#sha256=13c5e683b276d61c33598b616dd7b252730cdb6640daa5a18a1576dee3c9a3c1 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/04/8d/599fd744ddde741db36f9de641e894095ec9ada87630fa15db926e542c88/pyre_check-0.0.37-py3-none-manylinux1_x86_64.whl#sha256=4c33196d7423771b7b25b3dd7340ab60e5499e796e69f1aef1507e465d7466d0 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/c8/ff/eae80bb8a8f06caf104068f8a6064648fcb5f593be8742ded6c9278061e4/pyre_check-0.0.38-py3-none-macosx_10_11_x86_64.whl#sha256=0b83aaa201bb4de95ac9de4742b7798aea92017107005c3a565118423c6b70b9 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/28/79/0e7151ea2244d32dc71f22c40d1f39d71d6bbf1f7921df7522381ab751bc/pyre_check-0.0.38-py3-none-manylinux1_x86_64.whl#sha256=a7feed0bd53b92c5f94bdeb0b23dd250747f10b8bf1041ee270f4bf5cc6a0a14 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Found link https://files.pythonhosted.org/packages/09/f9/621fc5d7b034975024ff35d0ea89d90c91f4ecba37f4aa7101e15d68b505/pyre-check-0.0.39.tar.gz#sha256=5ea65dcd2b087e4226d9f6cc00961127358b1e4d7f5ea3766d7f1211a8b37f5e (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.39
  Skipping link: none of the wheel's tags match: py3-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/48/a0/e885bf47bed3578bf7e7d6d9223d80bb7801dc8367f2d25173b43773882c/pyre_check-0.0.39-py3-none-macosx_10_11_x86_64.whl#sha256=06984c1522166ee0355b3e4d0956841c3dfda821b8f7e099501cc9ea1b9d4e10 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/e5/18/feaa77522010ffbd4fa51be3347a03d04c6c05d4f9f64194c6b10e15c469/pyre_check-0.0.39-py3-none-manylinux1_x86_64.whl#sha256=d4144fa2dd6f7630c53edbad5fc6eba501d723bfeb57922a90d6be16fe0c0211 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5)
Given no hashes to check 6 links for project 'pyre-check': discarding no candidates
Using version 0.0.39 (newest of versions: 0.0.30, 0.0.31, 0.0.32, 0.0.36, 0.0.37, 0.0.39)
1 location(s) to search for versions of pyre-check:
* https://pypi.org/simple/pyre-check/
Fetching project page and analyzing links: https://pypi.org/simple/pyre-check/
Getting page https://pypi.org/simple/pyre-check/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pyre-check/" in the cache
Request header has "max_age" as 0, cache bypassed
https://pypi.org:443 "GET /simple/pyre-check/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/88/34/92d4ae95b9dc90084e5828c5e868de4bc0597ef944ef3d1968f39f716070/pyre-check-0.0.29-macosx_10_11_x86_64.tar.gz#sha256=f7872b0e8b6def017aaf71e2406f7067b40c3926a6ab3087fb0c9a5bd8214c5c (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.29-macosx_10_11_x86_64
  Found link https://files.pythonhosted.org/packages/69/4c/d45d75ff044075389b8f044fe9817648eb24a047cd55275674d1d9ee162b/pyre-check-0.0.30.tar.gz#sha256=f01a306401a48258edc32997064917a0ad7d110cc903ca6e31fbecf6ccccba17 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.30
  Found link https://files.pythonhosted.org/packages/97/c0/f7a1b73dbf71f3b58713cf246d594f23297ed5c5388afa198708e9a16e4b/pyre-check-0.0.31.tar.gz#sha256=918dbdf7d564ae158b2bfd507525ed760b32d772b5c82f88284f4672c01fe50f (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.31
  Found link https://files.pythonhosted.org/packages/1a/3e/ac9126cfb9db76746f9bfd1c224384ef5ed9a250d7a254bb5c917d63ee0b/pyre-check-0.0.32.tar.gz#sha256=58190046d0c374c9ee486c34e010a9c2795767699d13d56c23e3d7f619bff038 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.32
  Found link https://files.pythonhosted.org/packages/ac/c5/9eb377eaf32a2e63f1d62f518a5f89068e2071d0bf2b12ffb1973089ca99/pyre-check-0.0.36.tar.gz#sha256=130ddc4e3abf431a04f42845288149253a1f5a8804d3a03b4faca958805c2ee3 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.36
  Found link https://files.pythonhosted.org/packages/61/9f/2584ef32c5b39c05e8dcacf168b1b8039d5df5de0ad70a35a07be70e109e/pyre-check-0.0.37.tar.gz#sha256=ab012f2f2e7efed66b2452d32393505c79429fd123cf99efd6bed3f44c124cf5 (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.37
  Found link https://files.pythonhosted.org/packages/09/f9/621fc5d7b034975024ff35d0ea89d90c91f4ecba37f4aa7101e15d68b505/pyre-check-0.0.39.tar.gz#sha256=5ea65dcd2b087e4226d9f6cc00961127358b1e4d7f5ea3766d7f1211a8b37f5e (from https://pypi.org/simple/pyre-check/) (requires-python:>=3.5), version: 0.0.39
Given no hashes to check 6 links for project 'pyre-check': discarding no candidates
Using version 0.0.39 (newest of versions: 0.0.30, 0.0.31, 0.0.32, 0.0.36, 0.0.37, 0.0.39)
Collecting pyre-check
  Created temporary directory: /private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-unpack-_45nbk3r
  Looking up "https://files.pythonhosted.org/packages/09/f9/621fc5d7b034975024ff35d0ea89d90c91f4ecba37f4aa7101e15d68b505/pyre-check-0.0.39.tar.gz" in the cache
  Current age based on date: 429
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 429
  Using cached pyre-check-0.0.39.tar.gz (119 kB)
  Added pyre-check from https://files.pythonhosted.org/packages/09/f9/621fc5d7b034975024ff35d0ea89d90c91f4ecba37f4aa7101e15d68b505/pyre-check-0.0.39.tar.gz#sha256=5ea65dcd2b087e4226d9f6cc00961127358b1e4d7f5ea3766d7f1211a8b37f5e to build tracker '/private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-req-tracker-28k3mguy'
    Running setup.py (path:/private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-install-7s1hflj9/pyre-check/setup.py) egg_info for package pyre-check
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-install-7s1hflj9/pyre-check/setup.py", line 55, in <module>
        with open("README.md") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
Cleaning up...
  Removing source in /private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-install-7s1hflj9/pyre-check
Removed pyre-check from https://files.pythonhosted.org/packages/09/f9/621fc5d7b034975024ff35d0ea89d90c91f4ecba37f4aa7101e15d68b505/pyre-check-0.0.39.tar.gz#sha256=5ea65dcd2b087e4226d9f6cc00961127358b1e4d7f5ea3766d7f1211a8b37f5e from build tracker '/private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-req-tracker-28k3mguy'
Removed build tracker: '/private/var/folders/ml/kgz_nqm17zncq4rnkty4s40h0000gn/T/pip-req-tracker-28k3mguy'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 544, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 118, in generate_metadata
    command_desc='python setup.py egg_info',
  File "/Users/fallentree/src/libra-client-dev/python/venv/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by mattjw** [comment]
@MaggieMoss thank you!

In the meantime we switched to `0.0.30` as an interim workaround. This successfully builds on alpine (`python:3.6.8`), but then we encounter problems with `pyre.bin`.

## To reproduce via docker

```
docker run -it python:3.6.8 bash
```

Then install some prereqs:

```
cd /home
pip install pipenv
mkdir .venv
pipenv install pyre-check==0.0.30
pipenv install typeshed

# the following are unrelated to the problem (I think). this is
# a workaround because pyre is picky about what directories
# appear in the typeshed dir
mkdir .typeshed
cp -r .venv/lib/python3.6/site-packages/typeshed/stdlib/ .typeshed/stdlib
cp -r .venv/lib/python3.6/site-packages/typeshed/third_party/ .typeshed/third_party
```

And then run:

```
pipenv run pyre --typeshed=.typeshed --source-directory . check
```

Which gives error:

```
 ƛ Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
 ƛ [Errno 8] Exec format error: '/home/.venv/bin/pyre.bin'
 ƛ Traceback (most recent call last):
  File "/home/.venv/lib/python3.6/site-packages/pyre_check/pyre.py", line 530, in main
    command(arguments, configuration, analysis_directory)
  File "/home/.venv/lib/python3.6/site-packages/pyre_check/commands/command.py", line 135, in run
    self._run()
  File "/home/.venv/lib/python3.6/site-packages/pyre_check/commands/check.py", line 52, in _run
    result = self._call_client(command="check")
  File "/home/.venv/lib/python3.6/site-packages/pyre_check/commands/command.py", line 239, in _call_client
    preexec_fn=limit_memory_usage,
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/.venv/bin/pyre.bin'
```

## `0.0.24` suddenly broke

Maybe we're going a bit off the approved path here by using alpine.

Previously we were using `0.0.24` without issue. Recently, though, we stopped being able to pull that version from pypi:

```
$ pipenv install pyre==0.0.24

CRITICAL:pipenv.patched.notpip._internal.index:Could not find a version that satisfies the requirement pyre==0.0.24 (from versions: )
...
ERROR: ERROR: No matching distribution found for pyre==0.0.24
```

```
$ pip install pyre==0.0.24

Collecting pyre==0.0.24
  ERROR: Could not find a version that satisfies the requirement pyre==0.0.24 (from versions: none)
ERROR: No matching distribution found for pyre==0.0.24
WARNING: You are using pip version 19.1.1, however version 20.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by MaggieMoss** [comment]
I've just released a new version of Pyre that should solve this issue. 

I'm also actively working on adding new tests so we can prevent this in the future. 

Thanks so much for your patience!

**Comment by adrianbn** [comment]
Hi @MaggieMoss,

is it possible that 0.0.39 is still missing a README.md and that 0.0.38 has no tar.gz? Thanks!

**Comment by thefallentree** [comment]
I just tested 0.0.40 and venv/lib/pyre_check/typeshed directory is missing after install .

**Comment by adrianbn** [comment]
I have that same issue as well with 0.0.40 (no typeshed).

**Comment by MaggieMoss** [comment]
Apologies, putting a fix up for the missing typeshed now. Will have a working release by end of day.

**Comment by adrianbn** [comment]
Just as an FYI since this may still be a work in progress, but the current 0.0.41 is only shipping `pyre.bin` as a Mac-O executable and it is failing to run on Linux (CentOS 7 Python 3.6.8).

```
[centos@ip-10-204-252-12 ~]$ pip install pyre-check==0.0.41
Processing /home/centos/.cache/pip/wheels/7c/55/57/6995ccb17de05a9bcc781dd2637865529a418fdfe031f1a916/pyre_check-0.0.41-py3-none-any.whl
Requirement already satisfied: pyre-extensions in /home/centos/.local/share/virtualenvs/fortstarter-hziYG99A/lib/python3.6/site-packages (from pyre-check==0.0.41) (0.0.16)
Requirement already satisfied: pywatchman in /home/centos/.local/share/virtualenvs/fortstarter-hziYG99A/lib/python3.6/site-packages (from pyre-check==0.0.41) (1.4.1)
Requirement already satisfied: libcst in /home/centos/.local/share/virtualenvs/fortstarter-hziYG99A/lib/python3.6/site-packages (from pyre-check==0.0.41) (0.3.0)
Requirement already satisfied: psutil in /home/centos/.local/share/virtualenvs/fortstarter-hziYG99A/lib/python3.6/site-packages (from pyre-check==0.0.41) (5.6.7)
Requirement already satisfied: typing-inspect in /home/centos/.local/share/virtualenvs/fortstarter-hziYG99A/lib/python3.6/site-packages (from pyre-extensions->pyre-check==0.0.41) (0.5.0)
Requirement already satisfied: typing-extensions>=3.7.2 in /home/centos/.local/share/virtualenvs/fortstarter-hziYG99A/lib/python3.6/site-packages (from libcst->pyre-check==0.0.41) (3.7.4.1)
Requirement already satisfied: dataclasses; python_version < "3.7" in /home/centos/.local/share/virtualenvs/fortstarter-hziYG99A/lib/python3.6/site-packages (from libcst->pyre-check==0.0.41) (0.7)
Requirement already satisfied: mypy-extensions>=0.3.0 in /home/centos/.local/share/virtualenvs/fortstarter-hziYG99A/lib/python3.6/site-packages (from typing-inspect->pyre-extensions->pyre-check==0.0.41) (0.4.3)
Installing collected packages: pyre-check
Successfully installed pyre-check-0.0.41
[centos@ip-10-204-252-12 ~]$ file /home/centos/.local/share/virtualenvs/venv-test-hziYG99A/bin/pyre.bin
/home/centos/.local/share/virtualenvs/venv-test-hziYG99A/bin/pyre.bin: Mach-O 64-bit executable
```

This fails to run:
```
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/centos/.local/share/virtualenvs/venv-test-hziYG99A/bin/pyre.bin'
```

It works fine on my Mac though.

**Comment by adrianbn** [comment]
Also, quick question, will previous releases be fixed? (0.0.38, etc?) Or are we going to jump on `0.0.41` or upwards to get a working version?

**Comment by MaggieMoss** [comment]
@adrianbn 

> PyPI does not allow for a filename to be reused, even once a project has been deleted and recreated.

Once we've used a version number, we cannot update it. This is a great discussion on the topic: https://github.com/pypa/packaging-problems/issues/74

Because of this, in order to get the fix you'd need to update to `0.0.41`. 

Thank you so much for reporting the linux issue. I'll focus my attention there next.

**Comment by thefallentree** [comment]
confirmed 0.0.41 works for me both under linux and mac. Thanks!

**Comment by thefallentree** [comment]
@MaggieMoss  this reappeared again in 0.0.43,  after installation, typeshed directory is missing

./venv/lib/pyre_check/typeshed is not a valid directory.

**Comment by MaggieMoss** [comment]
@thefallentree  is this on linux or mac? I'll take a look now.

**Comment by thefallentree** [comment]
> @thefallentree Couple of questions:
> 
> is this on linux or mac? Did you install via the wheel or the tar? I'll take a look now.

I did pip install , and it fails both on osx and mac.
